#! /bin/sh
sxhkd &
compton -cGfF -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88 --frame-opacity 0.2 &
sh ~/.fehbg &
sh ~/.config/bspwm/window_gap


bspc config border_width		3
bspc config window_gap			6

bspc config top_padding			42
bspc config left_padding		22
bspc config right_padding		22
bspc config bottom_padding		22

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config history_aware_focus		true
bspc config focus_follows_pointer	true
bspc config center_pseudo_tiled		true


bspc config normal_border_color		"#000000"
bspc config focused_border_color	"#ffffff"
bspc config presel_feedback_color	"#51c4d4"


bspc monitor -d 1 2 3 4

bspc rule -a URxvt desktop=^1 follow=on
bspc rule -a URxvt:mc desktop=^3 follow=on
bspc rule -a Firefox desktop=^2 follow=on

bspc config single_monocle true
